FROM nodered/node-red:latest-minimal

# Kopiere package.json und installiere die Abhängigkeiten
WORKDIR /data
COPY node-red-data/package.json .
RUN npm install --unsafe-perm --no-update-notifier --no-fund --only=production 

# Kopiere die Node-RED Konfigurationsdateien
COPY node-red-data/settings.js .
COPY node-red-data/flows.json .
COPY node-red-data/flows_cred.json .

# Setze Arbeitsverzeichnis zurück
WORKDIR /usr/src/node-red