# Stage 1: Build your Go application
FROM golang:1.24 AS builder

# Install CA certificates
# RUN apt-get update && apt-get install -y ca-certificates

# Set the working directory
WORKDIR /app

# Copy Go modules and install dependencies
COPY go.mod go.sum ./ 
RUN go mod download

# Copy the source code
COPY . .
# Build the Go application
# RUN go build -o iot-gateway main.go
RUN CGO_ENABLED=0 go build -o iot-gateway main.go

# Stage 2: Set up the runtime environment
# FROM debian:bookworm-slim
FROM alpine:latest

# Füge tzdata hinzu, damit Zeitzoneninformationen verfügbar sind
RUN apk add --no-cache tzdata docker-cli

# set timezone Europe/Berlin
RUN cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Set up working directory
WORKDIR /app

# Copy the Go binary from the builder stage
COPY --from=builder /app/iot-gateway .

# Copy the WebUI files directly into the image
COPY --from=builder /app/webui/templates /app/webui/templates
COPY --from=builder /app/webui/assets /app/webui/assets

# Copy the SSL certificates
COPY --from=builder /app/server.crt /app/server.crt
COPY --from=builder /app/server.key /app/server.key

# Copy the iot_gateway.db
COPY --from=builder /app/iot_gateway.db /app/iot_gateway.db

RUN chmod +x /app/iot-gateway

# Expose necessary ports
EXPOSE 8088 5000 5001 5100 5101

# Command to run Go application
ENTRYPOINT [ "/app/iot-gateway" ]